### ISSUE TITLE
logger.warn is undefined if messageType is emtpy

### ISSUE THREAD

**Issue by sydcanem** [School-Improvement-Network/lapin#55]
I'm getting an error `Uncaught TypeError: Cannot read property 'warn' of undefined` whenever I send an empty `messageType` to req-res. We may need to move this line https://github.com/School-Improvement-Network/lapin/blob/master/lib/req-res/requester.js#L29 outside of the else block.

**Comment by openam** [comment]
@sydcanem looks like that line has changed. Did this get addressed?

**Comment by sydcanem** [comment]
Looks like it was addressed by commit 675c2d80. I'll verify if this is true.

**Comment by fakewaffle** [comment]
Is this still an issue?

**Comment by sydcanem** [comment]
It now returns a proper json error on response. Closing this as it is now fixed.
